### ISSUE TITLE
Exception으로 try, catch 작성된 코드 개선

### ISSUE THREAD

**Issue by woniper** [SpoonCode/SpooBlog#14]
예상치 못한 예외 상황을 잡기 위해서 Exception으로 try, catch문을 controller에 모두 코드를 작성했는데,
사실상 Exception으로 처리하는 예외상황은 좋은 상황은 아니에요.
그리고 구지 사용하자면 모든 코드에 Exception try, catch를 사용하는 것 보다는 ExControllerAdvice에 추가된 Exception 처리하는 코드처럼 처리하는게 코드 중복을 막을 수 있습니다.

*** 더 개선 해야 할 사항 ***
1. 많은 예외상황을 처리하는 코드 작성
2. log 찍기

**Comment by ParkMinKyu** [comment]
:ok: 그리고 시간있을때 헹아웃 함하자 merge를 로컬에서 하지말고 github에다가 pull-requests만들어서 하는게 날꺼같다. ㅋㅋ
